### ISSUE TITLE
Seeder Module

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1290]
Seeder is a top-level module that deals with import, export, seeding, data migration.

- [ ] Import/export atoms
- [ ] Import/export types
- [ ] Sync remote atoms/types locally

**Comment by webberwang** [comment]
https://github.com/codelab-ai/web/pull/1426/files Changed seeder here
