### ISSUE TITLE
Preliminary prop design, entity modeling

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#884]

**Comment by antonmihaylov** [comment]
### Types and props module overview
- Atom has Interface, which defines the API for the props it takes
- PageElement has Props, which are related to and validated by the Interface of the atom
- If a PageElement has no Atom, it can't have Props
- Interface must be able to reference other Interfaces, making the reusable
- Interface must have a way to include flexible types, like nested Interfaces, Arrays, Enums, Arrays of Interfaces, etc.
- Can't add fields with the same key to the same interface

## Use cases
- [ ] Interface
   - [ ] Create Interface
   - [ ] Get Interface (by Atom, by Id)
   - [ ] Update Interface
   - [ ] Add Field to Interface (separated from UpdateInterface, in order to reduce complexity)
   - [ ] Validate Interface (takes in arbitrary json data and validates in against the interface)
- [ ] Field
   - [ ] Create Field (maybe not needed, if we just use Add Field To Interface?)
   - [ ] 

- Prop CRUD
- Assign / Deassign Interface to Atom
- Assign / Deassign Props to PageElement
- Validate Props based on Interface
